server:
  port: 8080

spring:
  application:
    name: SECURE-BAG-API

  datasource:
    url: jdbc:mysql://localhost:3306/secure_bag?useSSL=false&serverTimezone=UTC
    username: root # wilverar
    password: 280101 # warraw*280101
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  secret:
    key: 8ebc070bb4a53120cd451cf58f4f48067decc4077a4b8d1f2a6632305cc4c299
  time:
    expiration: 86400000 # 1 day in milliseconds